### ISSUE TITLE
Update Console to match ext standards

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/react-console#31]
We'd like to check all extensions to try to update dependencies, node versions, etc. to ensure that our support is consistent across PF and our extensions.
- React 18 support, node 18
- Webpack 5 (and general dependencies update)
- A11y (at least testing on each PR)
- Linting - bump to version 8

**Comment by KKoukiou** [comment]
@jessiehuff to me it's not clear the exact missing standards. Maybe create some description? If someone else is going to work on it and is aware feel free to ignore.

**Comment by wise-king-sullyman** [comment]
It seems like as of #35 we are:

- Already on React 18 and supporting node 18
- Already using Webpack 5
- Already running a11y tests on each PR
- Already on version 8 of Eslint
