### ISSUE TITLE
Remove deprecated PatternFly components

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-console#47]
Components that were deprecated as part of the v5 PatternFly release are still in use.

[Those deprecated components](https://github.com/search?q=org%3Apatternfly+%2Fdeprecated+repo%3Apatternfly%2Freact-console+&type=code) should be replaced with the non-deprecated components or approaches PatternFly now recommends.

**Comment by jessiehuff** [comment]
Closed with https://github.com/patternfly/react-console/pull/48
